spring:
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: dali
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  thymeleaf:
    check-template-location: false
